FROM alpine:edge

RUN apk add --update --no-cache --force-overwrite crystal shards gc-dev libevent-dev libxml2-dev llvm llvm-dev llvm-libs llvm-static make musl-dev openssl openssl-dev pcre-dev readline-dev yaml-dev zlib-dev

