name: Docker images build

on:
  push:
    branches: ['*']
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: systemd-centos-7
            dockerfile: systemd/centos/7.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-centos:7
          - name: systemd-centos-8
            dockerfile: systemd/centos/8.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm64
            tags: |-
              jrei/systemd-centos:8
              jrei/systemd-centos:latest
          - name: systemd-debian-8
            dockerfile: systemd/debian/8.Dockerfile
            platforms: |-
              linux/amd64
            tags: |-
              jrei/systemd-debian:8
              jrei/systemd-debian:jessie
          - name: systemd-debian-9
            dockerfile: systemd/debian/9.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-debian:9
              jrei/systemd-debian:stretch
          - name: systemd-debian-10
            dockerfile: systemd/debian/10.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-debian:10
              jrei/systemd-debian:buster
              jrei/systemd-debian:latest
          - name: systemd-debian-11
            dockerfile: systemd/debian/11.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-debian:11
              jrei/systemd-debian:bullseye
          - name: systemd-debian-sid
            dockerfile: systemd/debian/sid.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-debian:sid
          - name: systemd-fedora-latest
            dockerfile: systemd/fedora/Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-fedora:latest
          - name: systemd-ubuntu-16.04
            dockerfile: systemd/ubuntu/16.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-ubuntu:16.04
              jrei/systemd-ubuntu:xenial
          - name: systemd-ubuntu-18.04
            dockerfile: systemd/ubuntu/18.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-ubuntu:18.04
              jrei/systemd-ubuntu:bionic
          - name: systemd-ubuntu-20.04
            dockerfile: systemd/ubuntu/20.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              jrei/systemd-ubuntu:20.04
              jrei/systemd-ubuntu:focal
              jrei/systemd-ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
