name: Docker images build

on:
  push:
    branches: ['*']
  schedule:
    - cron: '30 0 1 * *'

jobs:
  docker:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          # - os: ubuntu-22.04-arm
          #   arch: linux/arm64
          - os: ubuntu-latest
            arch: linux/amd64
        image:
          - path: openrc/alpine
            tags: |-
              jrei/openrc-alpine:latest
          - path: aports-dev
            tags: |-
              jrei/aports-dev:latest
          - path: systemd/centos
            version: "7"
            tags: |-
              jrei/systemd-centos:7
          - path: systemd/centos
            version: "8"
            tags: |-
              jrei/systemd-centos:8
              jrei/systemd-centos:latest
          - path: systemd/debian
            version: "11"
            tags: |-
              jrei/systemd-debian:11
              jrei/systemd-debian:bullseye
          - path: systemd/debian
            version: "12"
            tags: |-
              jrei/systemd-debian:12
              jrei/systemd-debian:bookworm
          - path: systemd/debian
            version: "13"
            tags: |-
              jrei/systemd-debian:13
              jrei/systemd-debian:trixie
              jrei/systemd-debian:latest
          - path: systemd/debian
            version: "sid"
            tags: |-
              jrei/systemd-debian:sid
          - path: systemd/fedora
            version: "41"
            tags: |-
              jrei/systemd-fedora:41
          - path: systemd/fedora
            version: "42"
            tags: |-
              jrei/systemd-fedora:42
          - path: systemd/fedora
            version: "43"
            tags: |-
              jrei/systemd-fedora:43
          - path: systemd/fedora
            version: "44"
            tags: |-
              jrei/systemd-fedora:44
              jrei/systemd-fedora:latest
          - path: systemd/ubuntu
            version: "22.04"
            tags: |-
              jrei/systemd-ubuntu:22.04
              jrei/systemd-ubuntu:jammy
          - path: systemd/ubuntu
            version: "24.04"
            tags: |-
              jrei/systemd-ubuntu:24.04
              jrei/systemd-ubuntu:noble
          - path: systemd/ubuntu
            version: "25.04"
            tags: |-
              jrei/systemd-ubuntu:25.04
              jrei/systemd-ubuntu:plucky
          - path: systemd/ubuntu
            version: "25.10"
            tags: |-
              jrei/systemd-ubuntu:25.10
              jrei/systemd-ubuntu:questing
          - path: systemd/ubuntu
            version: "26.04"
            tags: |-
              jrei/systemd-ubuntu:26.04
              jrei/systemd-ubuntu:resolute
              jrei/systemd-ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: jrei
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.image.name }} ${{ matrix.image.version }}
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: ${{ matrix.image.version && format('VERSION={0}', matrix.image.version) }}
          file: ${{ matrix.image.path }}/Dockerfile
          platforms: ${{ matrix.platform.arch }}
          push: true
          tags: ${{ matrix.image.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
